language: r
warnings_are_errors: false
sudo: true
dist: xenial
latex: false
cache: packages

matrix:
  fast_finish: true
  include:
    - os: linux
      r: release
      sudo: required
      dist: xenial
      cache:
        apt: true
      env:
        - BUILD_NAME=no_proj
        - R_CODECOV=true
        - DETAILS=""
    - os: linux
      r: release
      sudo: required
      dist: xenial
      cache:
        apt: true
      env:
        - BUILD_NAME=proj4
        - R_CODECOV=true
        - DETAILS=""
    - os: linux
      r: release
      sudo: required
      dist: xenial
      cache:
        apt: true
      env:
        - BUILD_NAME=proj5
        - R_CODECOV=true
        - DETAILS=""
    - os: linux
      r: release
      sudo: required
      dist: xenial
      cache:
        apt: true
      env:
        - BUILD_NAME=proj6
        - R_CODECOV=true
        - DETAILS=""
    - os: linux
      r: release
      sudo: required
      dist: xenial
      cache:
        apt: true
      env:
        - BUILD_NAME=proj7
        - R_CODECOV=true
        - DETAILS=""
    # - os: linux
    #   r: release
    #   sudo: required
    #   dist: xenial
    #   cache:
    #     apt: true
    #   env:
    #     - BUILD_NAME=ppa-libproj-dev
    #     - R_CODECOV=true
    #     - DETAILS=""

before_install:
  - ./ci/travis/${BUILD_NAME}/before_install.sh

after_success:
  - Rscript -e 'covr::codecov()'
